import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs/app-beta";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  className
}: {
  children: React.ReactNode,
  className: ""
}) {
  return (
    <html lang="en">
      <ClerkProvider>
      <div className={`w-full h-full inline-block z-0 bg-light p-32 ${className}`}>
      <body >{children}</body>
</div>      </ClerkProvider>
      
    </html>
  )
}
